# Initial login credentials:
# username: admin
# password: password
# When you change the password, the new password must be at least 8 characters
# long. However, this is not enforced in devMode. You should NOT use a password
# this week.  10+ chars, upper/lower case, & special chars is strongly recommended.

# config version is used indicate when breaking changes are made between
# versions of LeGo. Error will be logged and the /status endpoint will
# show mismatch if the version number of the config file and the LeGo binary
# do not match.
# If you see this, review the change log to determine what configuration
# item(s)need to be updated and then manually update the version number to
# clear the error.
config_version: 0

# Bind Address and Ports for API Server
# If address is blank, server will bind to all available addresses
# Https will start if there is a valid private_key and certificate
# pair specified below. If not, http starts.
# WARNING: You should obtain a valid certificate immediately to avoid loss
# of data confidentiality.
# Additionally, key and certificate downloads via the API key will be disabled
# if the server is running as http.
bind_address: ''
https_port: 4055
http_port: 4050

# enable http redirect - if this is enabled, when server is running
# https it will also start a server on the http port that will redirect
# the client to https
enable_http_redirect: true

# Server logging level (valid levels are: debug, info, warn, error, dpanic,
# panic, and fatal)
log_level: 'info'

# Should the server also host the frontend?
serve_frontend: true

# CORS permitted origins
# Only needed if the frontend is hosted somewhere other than the backend api server
# (i.e. at /app). Each entry should be a protocol + hostname or address + port 
# (e.g. https://localhost:5353 or http://192.168.1.1:5050)
# In most cases, this should not be used.
cors_permitted_origins: []

# API Server's key and cert
# These names should match the 'name' field of the desired key and cert within
# the application.
# If not specified (or invalid), a self-signed cert is created on each launch
# until proper values are specified.
private_key_name: legocerthub
certificate_name: legocerthub

# Development mode
# This should NOT be used in production!
# Specific changes:
# - Increased web server read/write timeouts
# - Increased http client timeouts
# - Allow 404 errors to be returned (in prod, 401 is returned instead of 404
#   to obfuscate if a route is valid or not)
# - Set log level to debug
# - Some functions are disabled until the server is running over https. devMode
#   enables those functions even when running over http. (e.g. change password,
#   download keys/certs, & redaction of certain sensitive informaiton before
#   it is returned to the client)
# - JSON marshal is indented
# - No change password complexity requirement
# - Set frontend to devMode (assuming backend hosts frontend)
#   see: https://github.com/gregtwallace/legocerthub-frontend/blob/master/src/helpers/environment.js
#   for more details regarding frontend changes
dev_mode: false

# Update checking functionality
updater:
  auto_check: true
  channel: beta

# Orders configuration
orders:
  # settings for automatic ordering
  auto_order_enable: true
  # order certs with less than this number of days remaining of validity
  valid_remaining_days_threshold: 40
  # time for the daily ordering to occur
  refresh_time_hour: 3
  refresh_time_minute: 12

# Challenge Providers
challenges:
  dns_checker:
    # specifying skip check wait disables dns record validation and instead
    # sleeps for the specified number of seconds and then assumes the record
    # is fully propagated
    skip_check_wait_seconds: null
    # services to use if checker is not disabled
    dns_services:
      # generally you do NOT want these to be internal dns servers
      # internal dns usually has long cache and doesn't truly check propagation
      # if you don't want external dns checking, use skip_check above
      - primary_ip: 1.1.1.1
        secondary_ip: 1.0.0.1
      - primary_ip: 9.9.9.9
        secondary_ip: 149.112.112.112
      - primary_ip: 8.8.8.8
        secondary_ip: 8.8.4.4
  providers:
    # http-01 internal server
    http_01_internal:
      enable: true
      # port to run the http challenge server on
      port: 4060
    # dns-01 using scripts that are external to LeGo
    dns_01_manual:
      enable: false
      environment:
        - "MY_EXPORT_VAR=some_value"
        - "ANOTHER_EXPORT_ENV=another_value"
      create_script: ./scripts/create-dns.sh
      delete_script: ./scripts/delete-dns.sh
    # acme-dns server (https://github.com/joohoi/acme-dns)
    # each name must be pre-registered and configured individually
    # LeGo only updates the challenge tokens automatically
    dns_01_acme_dns:
      enable: false
      acme_dns_address: http://localhost:8880
      resources: 
        # repeat this block as many times as needed
          # the actual domain you want a certificate for
        - real_domain: secure-server.example.com
          # the matching information about the acme-dns domain
          # that will be updated
          full_domain: ee29dc47-aaaa-aaaa-aaaa-aaaaaaaaaaaa.decoy.dummy.com
          username: ee29dc47-bbbb-bbbb-bbbb-bbbbbbbbbbbb
          password: QWDP...b2Mg
    # acme.sh scripts (https://github.com/acmesh-official/acme.sh)
    # complete dns-01 challenges with any provider supported by acme.sh
    # you will need to clone the repo and specify where the files are located
    dns_01_acme_sh:
      enable: false
      # path to the acme.sh script. /dnsapi subfolder must also exist and contain
      # the script for the relevant dns provider (hook script)
      acme_sh_path: ./scripts/acme.sh
      # for needed environment vars, review the relevant hook script
      # within acme.sh/dnsapi
      environment:
        - "MY_EXPORT_VAR=some_value"
        - "ANOTHER_EXPORT_ENV=another_value"
      # the --dns hook_name from acme.sh, this will match a filename in the
      # acme.sh/dnsapi path
      dns_hook: dns_cf

    # dns-01 via LeGo Cloudflare integration
    dns_01_cloudflare:
      enable: false
      accounts:
        - email: user@example.com
          global_api_key: 12345abcde
      tokens:
        - api_token: 123abc
          zone_names:
            - example.com
            - example1.com
            - example2.com
        - api_token: 345def
          zone_names:
            - example4.com

# EXPERIMENTAL AND UNSUPPORTED!!!

# override ACME directory (i.e. use a provider other than Let's Encrypt)
# This is not officially supported as I haven't tested other providers
# WARNING: External Binding is not yet implemented, so providers requiring this
# WILL NOT work.  Also, your database will become a mess if you change this
# setting and do not start a new database for the newly specified provider.
# YOU HAVE BEEN WARNED! CHANGE AT YOUR OWN RISK!
acme_prod_directory_url: "https://acme-v02.api.letsencrypt.org/directory"
acme_staging_directory_url: "https://acme-staging-v02.api.letsencrypt.org/directory"

# specify the ACME servers you wish to use. By default, only Let's Encrypt is enabled.
# Feel free to report bugs with other servers but only LE is officially supported.
acme_servers:
  # Should Let's Encrypt be enabled? (default: true)
  enable_lets_encrypt: true
  # Should Google Cloud be enabled? (default: false)
  enable_google_cloud: false
  # Array of custom defined ACME Servers of your choosing (default: none)
  # Custom ACME servers are an ADVANCED feature. Take special note of the 'db_value' field.
  custom_acme_servers:
    # A server
      # Friendly name that will display in the UI
    - name: "Your Provider"
      # string that will be used to save in the database. Once set you MUST NOT change
      # this value or you will cause big headaches for yourself and your database which
      # will likely require manual database editing to fix
      # ALL db_values must be unique and to avoid conflict with internal values, 'custom_'
      # will automatically be prepended to the value that is actually written to the db
      db_value: "some_provider_prod"
      # Is this a staging directory?
      staging: false
      # The URL the directory is hosted at
      directory_uri: https://prod.acme.example.com/directory
    # Another server
    - name: "Your Provider Staging"
      db_value: "some_provider_staging"
      staging: true
      directory_uri: https://staging.acme.example.com/directory
