# Host and Port for API Server (HTTPS/TLS)
# HTTPS will only be started if valid private_key and
# certificate names are specified below. Otherwise
# app is started with http for localhost only
hostname: "localhost"
https_port: 4055

# Port for HTTP (insecure) API Server
# Note: Hostname will ALWAYS be localhost for HTTP
http_port: 4050

# API Server's key and cert
# These names should match the 'name' field of the desired key and cert within
# the application.
# If not specified (or invalid), a self-signed cert is created on each launch
# until proper values are specified.
private_key_name: legocerthub
certificate_name: legocerthub

# Development mode
# This should NEVER be true in production
# Disables key SECURITY features!
dev_mode: false
